### ISSUE TITLE
Missing comma in install_requires

### ISSUE THREAD

**Issue by Boudewijn26** [bonitoo-io/ipython-flux#4]
[There is a missing comma in the list of `install_requires` in `setup.py`](https://github.com/bonitoo-io/ipython-flux/blob/master/setup.py#L18)

I encountered this as an issue when upgrading from poetry 1.1.x to 1.2.x. My fix was to remove the `poetry.lock` file, but still got a warning on `poetry install`

**Comment by bednar** [comment]
Hi @Boudewijn26,

thanks for using our integration. The issue is fixed in version `0.0.6` - https://pypi.org/project/ipython-flux/0.0.6/

Regards
